import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Game from './game'
import {useState} from 'react'
import {io, Socket} from 'socket.io-client'

const Home: NextPage = () => {
    
    const [game, setGame] = useState(false)
    const [username, setUsername] = useState("")
    const [socket, setSocket] = useState<Socket>()
    
    return !game || socket == undefined ? (
	<div className={styles.container}>
	    <Head>
		<title>Create Next App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	    </Head>
	
	    <h1>Hello</h1>
	    <button onClick={() => {
		let name = window.prompt("Name: ")
		while(typeof name != 'string' || name.length < 1)
		    name = window.prompt("Name: ")
		
		const s = io("http://localhost:6942")
		setSocket(s)	

		setUsername(name)
		alert(name)
		setGame(true)

		s.emit("join", {
		    name: name
		})
	    }}>JOIN GAME</button>
	</div>
    ) : (
	<Game socket={socket} name={username}/>
    )
}

export default Home

