import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { io } from 'socket.io-client'
import Router from 'next/router'

const socket = io("http://localhost:6942")
socket.on("amongus", () => {
    console.log("THINGS WERE SENT TO YOU")
})
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
	<Head>
	    <title>Create Next App</title>
	    <meta name="description" content="Generated by create next app" />
	    <link rel="icon" href="/favicon.ico" />
	</Head>
	
	<h1>Hello</h1>
	<button onClick={() => {
	    let name = window.prompt("Name: ")

	    alert(name)
	    Router.push("/amongus")
	}}>JOIN GAME</button>
    </div>
  )
}

export default Home

